planetelevain/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
	url(r'^recettes/', include('recettes.urls')),
    url(r'^admin/', admin.site.urls),
]

recettes/urls.py
from django.conf.urls import url

from . import views

app_name = 'recettes'
urlpatterns = [
	url(r'^$', views.index, name='index'),
	url(r'^(?P<recipe_id>[0-9]+)/$', views.index, name='detail'),
]

recettes/models.py
from django.db import models

class Ingredient(models.Model):
	name = models.CharField(max_length=200)
	price_per_kg = models.DecimalField(max_digits=5, decimal_places=2)
	
	def __str__(self):
		return self.name

class Recipe(models.Model):
	name = models.CharField(max_length=200)
	description = models.TextField()
	ingredients = models.ManyToManyField(Ingredient, through='IngredientsList')

	def __str__(self):
		return self.name

class IngredientsList(models.Model):
	recipe = models.ForeignKey(Recipe)
	ingredient = models.ForeignKey(Ingredient)
	weight_for_100g = models.IntegerField()

	def __str__(self):
		return "{0}: {2}g de {1}".format(self.recipe, self.ingredient, self.weight_for_100g)

recettes/forms.py
from django import forms
from .models import Recipe

class SelectRecipeForm(forms.Form):
	recipe = forms.ChoiceField(widget=forms.Select(attrs={"onChange":'this.form.submit()'}), choices=Recipe.objects.all().values_list('pk', 'name'), required=True, label="Recette")

class BatchCompositionForm(forms.Form):
	bread_qty = forms.ChoiceField(choices=[(a,b) for a,b in zip(range(1,101),range(1,101))], required=True, label="Nombre de pains ")
	bread_weight = forms.ChoiceField(choices=[(a,b) for a,b in zip(range(100,2100,100),range(100,2100,100))], required=True, label="Poids")

class RecipeForm(forms.ModelForm):
	class Meta:
		model = Recipe
		fields = "__all__"

recettes/views.py
from django.shortcuts import render, get_object_or_404
from .models import Recipe, IngredientsList
#nécessaire pour faire fonctionner makemigrations quand la base est vide
import sys
if 'makemigrations' not in sys.argv and 'migrate' not in sys.argv:
	from .forms import SelectRecipeForm, BatchCompositionForm


def index (request, recipe_id=''):
	recipes_list = Recipe.objects.all
	context = {'recipes_list': recipes_list}
		
	select_recipe_form = SelectRecipeForm(request.POST or None)
	batch_composition_form = BatchCompositionForm(request.POST or None)

	if select_recipe_form.is_valid():
		#selected_choice = question.choice_set.get(pk=request.POST['choice'])
		selected_recipe = Recipe.objects.get(pk=select_recipe_form.cleaned_data['recipe'])

	if batch_composition_form.is_valid():
		bread_qty = batch_composition_form.cleaned_data['bread_qty']
		bread_weight = batch_composition_form.cleaned_data['bread_weight']
		ingredients_list = IngredientsList.objects.filter(recipe=selected_recipe.id)
		ingredient_list_with_total=[]
		for item in ingredients_list:
			ingredient_list_with_total.append({
				'name': item.ingredient,
				'weight': item.weight_for_100g,
				'total': int(int(bread_qty) * int(bread_weight) * (item.weight_for_100g / 100)),
				'price_per_kg': item.ingredient.price_per_kg
				})
			
	return render(request, 'recettes/index.html', locals())

def detail (request, recipe_id):
	recipe = get_object_or_404(Recipe, pk=recipe_id)
	return render(request, 'recettes/details.html', {'recipe': recipe})

recettes/templates/recettes/index.html
<html>
	<head>
		<meta charset="utf-8">
    	<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<title>Planete Levain : recettes</title>
		<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
		<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
		
	</head>
	<body>
		<div class="container">
			<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
	    	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
	    	<!-- Include all compiled plugins (below), or include individual files as needed -->
	    	<!--<script src="js/bootstrap.min.js"></script>-->

			<div class="page-header">
				<h1>Liste des recettes</h1>
			</div>
		{% if recipes_list %}	
			<div>
				<p> <form action="{% url 'recettes:index' %}" method="POST">
					{% csrf_token %}
					{{ form.non_field_errors }}
					<p class="lead"> Choisis une recette: {{ select_recipe_form.recipe }}</p>
				</p>
			</div>
			{% if select_recipe_form.is_valid %}
			<div>
				<p class="lead"><b>Description:</b> {{ selected_recipe.description }}</p>
			</div>
			<br>
			<div class="well">
				<p><form action="{% url 'recettes:index' %}" method="POST">
				{% csrf_token %}
				{{ form.non_field_errors }}
				{{ batch_composition_form.bread_qty.label_tag }} {{  batch_composition_form.bread_qty }}
				{{ batch_composition_form.bread_weight.label_tag }} {{  batch_composition_form.bread_weight }}
				<input type="submit" value="Calculer" class="btn btn-primary"/>
				</form></p>
			</div>
			<div>
			<h3>Composition</h3>
				<table class="table">
				<tr>
					<th>Ingrédient</th>
					<th>Quantité</th>
					<th>Prix au kg</th>
				</tr>
				{% for item in ingredient_list_with_total %}
				<tr>
					<td>{{ item.name }}</td>
					<td>{{ bread_qty}} x {{ bread_weight }} x {{ item.weight }} = <b>{{ item.total }}g</b> </td>
					<td><i>{{ item.price_per_kg }} €/kg</i></td>
				</tr>
				{% endfor %}
				<tr>{{ a }}</tr>
				</table>
			</div>
			<br>
			<div>
			<p>Prix de revient:</p>
			</div>
			{% endif %}
		{% else %}
			<p>Pas de recettes</p>
		{% endif %}
		</div>
	</body>
</html>